# JMeter CSV 输出格式配置
# 必须 CSV 格式才能生成 HTML 报告
jmeter.save.saveservice.output_format=csv
jmeter.save.saveservice.response_data=false
jmeter.save.saveservice.samplerData=false
jmeter.save.saveservice.requestHeaders=false
jmeter.save.saveservice.responseHeaders=false
jmeter.save.saveservice.encoding=false
jmeter.save.saveservice.assertions=true
jmeter.save.saveservice.latency=true
jmeter.save.saveservice.connect_time=true
jmeter.save.saveservice.samplerData=false
jmeter.save.saveservice.timestamp_format=ms
jmeter.save.saveservice.time=true
jmeter.save.saveservice.code=true
jmeter.save.saveservice.message=true
jmeter.save.saveservice.success=true
jmeter.save.saveservice.label=true
jmeter.save.saveservice.threadName=true
jmeter.save.saveservice.bytes=true
jmeter.save.saveservice.sentBytes=true
jmeter.save.saveservice.url=true
jmeter.save.saveservice.threadCounts=true
jmeter.save.saveservice.idleTime=true
# 减少 GUI 渲染开销
jmeter.gui.refresh_period=5
