"""生成 _build_info.py：写入版本号、构建日期、Git SHA。

供 About API 与 /api/about/check-update 读取。
由 scripts/重新构建.bat 末尾自动调用。

幂等：每次运行覆盖写入，不做时间戳累加。
容错：git 不可用时 git_sha 写 "unknown"，不中断构建。
"""
from __future__ import annotations

import subprocess
import sys
from datetime import datetime
from pathlib import Path

# _build_info.py 输出路径：backend/xianyu_hunter/_build_info.py
PKG_ROOT = Path(__file__).resolve().parents[1] / "backend" / "xianyu_hunter"
INIT_FILE = PKG_ROOT / "__init__.py"
OUT_FILE = PKG_ROOT / "_build_info.py"
# 项目根目录（用于 git rev-parse）
PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _git_sha() -> str:
    """读取当前 commit 的短 SHA；git 不可用时返回 'unknown'。"""
    try:
        result = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL,
            cwd=PROJECT_ROOT,
            timeout=3,
        )
        sha = result.decode().strip()
        return sha if sha else "unknown"
    except Exception:
        return "unknown"


def _read_version() -> str:
    """从 __init__.py 解析 __version__ = "x.y.z"。

    失败兜底 "unknown"，不中断构建。
    """
    try:
        text = INIT_FILE.read_text(encoding="utf-8")
    except Exception:
        return "unknown"
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("__version__"):
            try:
                # __version__ = "0.1.0" 或 __version__ = '0.1.0'
                value = stripped.split("=", 1)[1].strip().strip('"').strip("'")
                return value
            except Exception:
                return "unknown"
    return "unknown"


def main() -> int:
    version = _read_version()
    sha = _git_sha()
    build_date = datetime.now().strftime("%Y-%m-%d")
    content = (
        "# Auto-generated by scripts/build_info.py; do not edit.\n"
        f'__version__ = "{version}"\n'
        f'build_date = "{build_date}"\n'
        f'git_sha = "{sha}"\n'
    )
    OUT_FILE.write_text(content, encoding="utf-8")
    print(f"[build_info] version={version} build_date={build_date} git_sha={sha}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
